spring.application.name=Smart City Complaint Management System
server.port=8080

spring.datasource.url=jdbc:postgresql://postgres:5432/smart_city_db
spring.datasource.username=postgres
spring.datasource.password=Barasat@100

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anubhabbarasat100@gmail.com
spring.mail.password=aqoqrqiinbkpxykl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

ML_VALIDATION_API_URL=http://python-api:5000/predict
ML_PRIORITY_API_URL=http://python-api:5000/predict/priority
ML_CATEGORY_API_URL=http://python-api:5000/predict/category
MINIMUM_CONFIDENCE_THRESHOLD=0.5
MAXIMUM_CONFIDENCE_THRESHOLD=0.8

REGISTERED_COMPLAINT_PATH=/templates/registered_complaint.html
DASHBOARD_URL=http://127.0.0.1:5500/citizen-dashboard.html
AUTHORITY_DASHBOARD_URL=http://127.0.0.1:5500/citizen-dashboard.html
REGISTERED_COMPLAINT_AUTHORITY_PATH=/templates/registered_complaint_authority.html
OTP_VERIFICATION_TEMPLATE_PATH=/templates/otp_verification.html